#!/usr/bin/env node
// scripts/build-config.mjs
// Generate js/config.local.js from environment variables at build time.
// Skips silently if env vars are absent (local dev manages config.local.js
// by hand). Designed to run as Vercel's buildCommand.

import { writeFile, access } from "node:fs/promises";
import { constants } from "node:fs";

const url = process.env.SUPABASE_URL;
const key = process.env.SUPABASE_ANON_KEY;
const passphrase = process.env.OWNER_PASSPHRASE;

const OUT = "js/config.local.js";

if (!url || !key) {
  // No env vars — assume local dev where config.local.js is committed-by-hand
  // (gitignored). Don't overwrite.
  try {
    await access(OUT, constants.F_OK);
    console.log(`[build-config] no env vars; ${OUT} already exists, skipping.`);
  } catch {
    console.warn(
      `[build-config] no env vars and no ${OUT}. ` +
        "Pages requiring Supabase will fail to load.",
    );
  }
  process.exit(0);
}

if (!passphrase || passphrase === "set-me") {
  console.warn(
    "[build-config] OWNER_PASSPHRASE not set (or = 'set-me'). " +
      "Editor pages will block all access. Set it before deploying.",
  );
}

const content =
  "// Generated by scripts/build-config.mjs from env vars at build time.\n" +
  `window.SUPABASE_URL      = ${JSON.stringify(url)};\n` +
  `window.SUPABASE_ANON_KEY = ${JSON.stringify(key)};\n` +
  `window.OWNER_PASSPHRASE  = ${JSON.stringify(passphrase || "set-me")};\n`;

await writeFile(OUT, content);
console.log(`[build-config] ✓ ${OUT} written from env (${content.length}B).`);
